# application-dev.yml
search:
  api:
    key: ${SEARCH_API_KEY}
  timeout-seconds: 4 # Brave 검색 타임아웃

llm:
  model: gemini-2.0-flash-lite
  api:
    key: ${LLM_API_KEY}
  timeout-seconds: 8 # Gemini 타임아웃


app:
  jsoup:
    http-timeout-ms: 2000
    future-timeout-ms: 3000
    thread-pool-size: 8

spring:
  cache:
    cache-names: sourceCache, llmResultCache,  # LLM 답변 + 출처 캐시, 검색결과 캐시
    type: redis  # 전체 캐시 타입을 Redis로
  data:
    redis:
      host: redis-17439.c11.us-east-1-3.ec2.cloud.redislabs.com
      port: 17439
      password: ${REDIS_PASSWORD}  # 없으면 이 줄 삭제
#      ssl:
#        enabled: true
